### ISSUE TITLE
game can't start

### ISSUE THREAD

**Issue by rogerthegnome** [mopioid/Borderlands-Commander#23]
hi, i've downloaded everything followed the tutorial and shit, blcmm works fine no error or anything, commander works fine too, but when i launch bl2 the mini launcher of the game appears, and after i click on play the game closes itself without any errors, does any one knows what's going on ?

**Comment by rogerthegnome** [comment]
ok it seems to be the file ddraw.dll that causes issues because when deleted it the game launched

**Comment by DeathCounterr** [comment]
> ok it seems to be the file ddraw.dll that causes issues because when deleted it the game launched

Hello, I have the same problem and I know how to fix it. 
I don't know if it will fix your problem but that fixed for me 
First: download back ddraw.dll
Second: put it again in Win32
Third: The Winrar/Zip for CommanderInjector instead of putting "CommandInjector" in Plugins put "CommandInjector-UHD.dll" 
That fixed for me and I don't think you need UHD for Borderlands to work because it fixed for me and I don't use that UHD

**Comment by CyberNinja04** [comment]
> > ok it seems to be the file ddraw.dll that causes issues because when deleted it the game launched
> 
> Hello, I have the same problem and I know how to fix it.
> I don't know if it will fix your problem but that fixed for me
> First: download back ddraw.dll
> Second: put it again in Win32
> Third: The Winrar/Zip for CommanderInjector instead of putting "CommandInjector" in Plugins put "CommandInjector-UHD.dll"
> That fixed for me and I don't think you need UHD for Borderlands to work because it fixed for me and I don't use that UHD

That fixed it for me too, i dont use UHD pack and thats what it needed, im guessing UHD just means the "update" not the dlc you can deselect/select from steam library
