### ISSUE TITLE
I dont find the borderlands commander.exe

### ISSUE THREAD

**Issue by imno45** [mopioid/Borderlands-Commander#6]
It may sound stupid but i really dont find the borderlands  commander .
i dowanloaded all the files but i dont find it

**Comment by CorbinDRC** [comment]
I'm having the same issue, there isn't a borderlands commander.exe in any of the files

**Comment by CorbinDRC** [comment]
I've seriously been trying to find this or an answer to this problem with no luck. I was hoping that if someone else had this problem there would at least be some answers but clearly not. Also, the download link for commander in the instructions has a Trojan attached to it.

**Comment by CorbinDRC** [comment]
The lack of any kind of response to issues is infuriating.

**Comment by c0dycode** [comment]
Then your Antivirus software most likely deletes the exe.
If you download the zip file for BL Commander, there is only the exe inside.

![image](https://user-images.githubusercontent.com/3851319/45892729-43e5a600-bdc9-11e8-85e3-a50a88d0e828.png)

**Comment by CorbinDRC** [comment]
Do you know how to bypass this?

**Comment by c0dycode** [comment]
Most antivirus software have either a way to revert deletion, you simply add an exception for it or temporarily disable it. That's up to your antivirus software though. You should be able to find out how to do either fairly easily with google.

**Comment by CorbinDRC** [comment]
Okay, I'll look and see. Thanks so much bruv.

On Sep 21, 2018 12:54 PM, "c0dycode" <notifications@github.com> wrote:

Most antivirus software have either a way to revert deletion, you simply
add an exception for it or temporarily disable it. That's up to your
antivirus software though. You should be able to find out how to do either
fairly easily with google.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mopioid/Borderlands-Commander/issues/6#issuecomment-423603473>,
or mute the thread
